/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Language } from '../types';

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  en: {
    title: 'Ultimate Snake Game',
    play: 'Play Game',
    classic: 'Classic Mode',
    timed: 'Timed Mode',
    adventure: 'Adventure Mode',
    zen: 'Zen Mode',
    endless: 'Endless Mode',
    survival: 'Survival Mode',
    maze: 'Maze Mode',
    speedrun: 'Speed Run Mode',
    boss: 'Boss Mode',
    classic_desc: 'Endless play, speed increases, highest-score chase.',
    timed_desc: 'Score max points in 120 seconds. Faster golden apples.',
    adventure_desc: 'Progressive levels (1-20). Obstacles & target goals.',
    zen_desc: 'No death, pastel themes, soothing ambient sounds.',
    endless_desc: 'Chill play without barriers or self-intersection crashes.',
    survival_desc: 'Aggressive obstacle spawns & tick speed acceleration.',
    maze_desc: 'Navigate full brick mazes without touching obstacles.',
    speedrun_desc: 'Race against time at insane speeds to gather 50 apples.',
    boss_desc: 'Avoid clever moving AI enemy snakes chasing you!',
    settings: 'Game Settings',
    high_scores: 'High Scores',
    install_app: 'Install PWA App',
    resume: 'Resume Match',
    restart: 'Restart Level',
    main_menu: 'Main Menu',
    game_over: 'Game Over!',
    new_high_score: 'New High Score!',
    play_again: 'Play Again',
    share_score: 'Share Result',
    replay_final: 'Watch Replay',
    duration_active: 'Active:',
    score: 'Score',
    high_score: 'High Score',
    length: 'Length',
    lives: 'Lives',
    level: 'Level',
    target: 'Target',
    time: 'Time',
    tutorial_skip: 'Skip Tutorial',
    tut_step_1_title: 'Swipe or Tap to Steer',
    tut_step_1_desc: 'Swipe anywhere, use the D-Pad, or set One-Tap relative controls in Settings to turn your snake.',
    tut_step_2_title: 'Eat to Grow & Bonus Foods',
    tut_step_2_desc: 'Eat Red Apples to grow. Collect Golden Apples, Lightning speeds, Turtle slows, or Star double-scores!',
    tut_step_3_title: 'Unleash Shield Power-Ups',
    tut_step_3_desc: 'Collect Shields for one-time protection from crashes, ×2 Multipliers, or Shrink tails to shorten length!',
    tut_step_4_title: 'Avoid Walls and Barriers',
    tut_step_4_desc: 'In Advanced mode, navigate around solid obstacles. Crashing terminates the game unless you have a Shield active.',
    wall_wrap: 'Wall Wrapping',
    wall_wrap_on: 'Wrap Enabled',
    wall_wrap_off: 'Solid Walls',
    snake_skin: 'Snake Skin Cosmetic',
    board_theme: 'Grid Board Theme',
    control_scheme: 'Steering Control Scheme',
    game_speed: 'Base Speed Profile',
    vibration: 'Tactile Haptics',
    sound_vol: 'SFX Sound Volume',
    music_vol: 'Ambient Music Volume',
    language: 'Interface Language',
    skin_classic: 'Emerald Green',
    skin_neon: 'Neon Laser Glow',
    skin_gradient: 'Ocean Gradient',
    skin_rainbow: 'Psychedelic Rainbow',
    skin_outline: 'Minimalist Contour',
    theme_default: 'Cosmic Slate',
    theme_grid: 'Classic Wireframe',
    theme_retro: 'Console Green Mono',
    theme_dark: 'Midnight Void',
    theme_high_contrast: 'Tactile Outline',
    theme_pastel: 'Zen Lilac Pastel',
    speed_slow: 'Slow (Easy)',
    speed_normal: 'Normal (Medium)',
    speed_fast: 'Fast (Challenging)',
    speed_insane: 'Insane (Hyper)',
    control_swipe: 'Swipe Anywhere',
    control_dpad: 'On-Screen D-Pad',
    control_onetap: 'One-Tap Clockwise',
    control_keyboard: 'WASD / Arrow Keys',
    shared_text: 'I just scored {score} points and reached length {length} in Ultimate Snake! Can you beat my record?',
    no_scores: 'No high scores saved yet. Take the crown!',
    level_completed: 'Level {level} Cleared!',
    level_congrats: 'Get ready for the next challenge!',
    continue_nxt: 'Proceed to Level {level}',
    tip_jar: 'Tip the Developer / Support',
    tip_jar_desc: 'If you enjoy Ultimate Snake, consider showing support!',
    replaying: 'Replaying Final Moments...',
    stop_replay: 'Exit Replay',
  },
  es: {
    title: 'Serpiente Definitiva',
    play: 'Jugar Partido',
    classic: 'Modo Clásico',
    timed: 'Contra Reloj',
    adventure: 'Aventura Progresiva',
    zen: 'Tranquilidad Zen',
    endless: 'Modo Infinito',
    survival: 'Modo Supervivencia',
    maze: 'Laberinto Completo',
    speedrun: 'Carrera Veloz',
    boss: 'Jefe Desafío',
    classic_desc: 'Juego infinito, rapidez incremental, busca del récord.',
    timed_desc: 'Consigue puntos máximos en 120 segundos. Manzanas de oro frecuentes.',
    adventure_desc: 'Niveles del 1 al 20, laberintos con obstáculos y metas.',
    zen_desc: 'Inmortal, temas pastel, música tranquila y ambientación.',
    endless_desc: 'Juego relajante sin muros divisorios ni colisiones contra tu propio cuerpo.',
    survival_desc: 'Apariciones constantes de obstáculos letales y velocidad vertiginosa.',
    maze_desc: 'Navega por muros de ladrillo sin cometer colisiones destructivas.',
    speedrun_desc: 'Consigue comer 50 manzanas tan rápido como puedas a una velocidad increíble.',
    boss_desc: 'Esquiva e intercepta serpientes enemigas controladas por IA.',
    settings: 'Ajustes del Juego',
    high_scores: 'Mejores Marcas',
    install_app: 'Instalar Aplicación',
    resume: 'Continuar',
    restart: 'Reiniciar Nivel',
    main_menu: 'Menú principal',
    game_over: '¡Juego Terminado!',
    new_high_score: '¡Nuevo Récord!',
    play_again: 'Volver a Jugar',
    share_score: 'Compartir Puntuación',
    replay_final: 'Ver Repetición',
    duration_active: 'Activo:',
    score: 'Puntos',
    high_score: 'Máximo',
    length: 'Longitud',
    lives: 'Vidas',
    level: 'Nivel',
    target: 'Meta',
    time: 'Tiempo',
    tutorial_skip: 'Saltar',
    tut_step_1_title: 'Desliza o Presiona',
    tut_step_1_desc: 'Usa gestos de deslizar, botones direccionales, o el modo Un-Toque en Ajustes para girar la serpiente.',
    tut_step_2_title: 'Comer y Crecer',
    tut_step_2_desc: 'Come manzanas rojas para crecer. ¡Atrapa manzanas doradas, rayos veloces, tortugas lentas o estrellas dobles!',
    tut_step_3_title: 'Poderes del Escudo',
    tut_step_3_desc: '¡Consigue escudos protectores contra los muros, multiplicadores por dos, o encoge la cola para acortar longitud!',
    tut_step_4_title: 'Evita los Obstáculos',
    tut_step_4_desc: 'En modo avanzado, esquiva barreras sólidas. Chocar destruye la serpiente a menos que tu escudo esté activo.',
    wall_wrap: 'Atravesar Paredes',
    wall_wrap_on: 'Traspaso Activado',
    wall_wrap_off: 'Paredes Sólidas',
    snake_skin: 'Aspecto Cosmético',
    board_theme: 'Tema del Tablero',
    control_scheme: 'Esquema de Control',
    game_speed: 'Velocidad de Base',
    vibration: 'Vibración Táctil',
    sound_vol: 'Volumen de Efectos',
    music_vol: 'Música de Fondo',
    language: 'Idioma de Interfaz',
    skin_classic: 'Verde Esmeralda',
    skin_neon: 'Resplandor de Neón',
    skin_gradient: 'Gradiente Marino',
    skin_rainbow: 'Arcoíris Psicodélico',
    skin_outline: 'Línea Minimalista',
    theme_default: 'Pizarra Cósmica',
    theme_grid: 'Malla Tradicional',
    theme_retro: 'Consola Verde Retro',
    theme_dark: 'Vacío Nocturno',
    theme_high_contrast: 'Alto Contraste Sólido',
    theme_pastel: 'Zen Malva Pastel',
    speed_slow: 'Lento (Fácil)',
    speed_normal: 'Normal (Medio)',
    speed_fast: 'Rápido (Difícil)',
    speed_insane: 'Extremo (Locura)',
    control_swipe: 'Deslizar Pantalla',
    control_dpad: 'Cruceta On-Screen',
    control_onetap: 'Giro Un-Toque',
    control_keyboard: 'Teclado WASD / Flechas',
    shared_text: '¡Acabo de anotar {score} puntos con la longitud {length} en Serpiente Definitiva! ¿Puedes superarme?',
    no_scores: '¡Aún no hay puntuaciones! ¡Sé el primero!',
    level_completed: '¡Nivel {level} Superado!',
    level_congrats: '¡Prepárate para el siguiente desafío!',
    continue_nxt: 'Ir al Nivel {level}',
    tip_jar: 'Apoyar al Desarrollador',
    tip_jar_desc: 'Si te gusta Serpiente Definitiva, considera apoyarnos.',
    replaying: 'Repitiendo Últimos Momentos...',
    stop_replay: 'Salir de Repetición',
  },
  fr: {
    title: 'Serpente Ultime',
    play: 'Jouer la Partie',
    classic: 'Mode Classique',
    timed: 'Chrono Minute',
    adventure: 'Aventure Niveaux',
    zen: 'Tranquillité Zen',
    endless: 'Mode Infini',
    survival: 'Mode Survie',
    maze: 'Mode Labyrinthe',
    speedrun: 'Course de Vitesse',
    boss: 'Combat de Boss',
    classic_desc: 'Mode infini, vitesse croissante, poursuite du meilleur score.',
    timed_desc: 'Score max en 120 secondes. Pommes dorées plus régulières.',
    adventure_desc: 'Niveaux progressifs (1-20). Obstacles fixes et mobiles.',
    zen_desc: 'Immortalité, thèmes pastel doux, mélodies calmes.',
    endless_desc: 'Mode détente sans limites ni écrasement de queue.',
    survival_desc: 'Apparitions brutales d\'obstacles mobiles et accélérations folles.',
    maze_desc: 'Traversez des structures en brique sans percuter de bordure.',
    speedrun_desc: 'Engrangez 50 pommes le plus vite possible à une vitesse folle.',
    boss_desc: 'Évitez les serpents hostiles de l\'IA qui patrouillent la carte.',
    settings: 'Options du Jeu',
    high_scores: 'Feuille des Scores',
    install_app: 'Installer l\'Application',
    resume: 'Reprendre',
    restart: 'Recommencer',
    main_menu: 'Menu Principal',
    game_over: 'Partie Terminée!',
    new_high_score: 'Nouveau Record!',
    play_again: 'Rejouer',
    share_score: 'Partager le Score',
    replay_final: 'Séquence Replay',
    duration_active: 'Actif:',
    score: 'Points',
    high_score: 'Meilleur',
    length: 'Longueur',
    lives: 'Vies',
    level: 'Niveau',
    target: 'Cible',
    time: 'Chrono',
    tutorial_skip: 'Passer le Manuel',
    tut_step_1_title: 'Glisser ou Tapoter',
    tut_step_1_desc: 'Glissez n\'importe où, utilisez le D-Pad virtuel, ou réglez le mode "One-Tap" pour tourner de manière relative.',
    tut_step_2_title: 'Grandir et Pommes Bonus',
    tut_step_2_desc: 'Mangez les pommes rouges. Ramassez les Pommes Dorées, Éclair vitesse, Tortue lente ou Étoile double-score !',
    tut_step_3_title: 'Bouclier de Protection',
    tut_step_3_desc: 'Attrapez un Bouclier pour parer un choc, profitez de Multiplicateurs x2, ou raccourcissez votre queue !',
    tut_step_4_title: 'Esquivez les Murs',
    tut_step_4_desc: 'En mode avancé, esquivez les barrières rigides. Les chocs sont fatals sans bouclier de sécurité.',
    wall_wrap: 'Passage des Murs',
    wall_wrap_on: 'Traversée Libre',
    wall_wrap_off: 'Murs Solides',
    snake_skin: 'Apparence du Serpent',
    board_theme: 'Style de Grille',
    control_scheme: 'Contrôle Direction',
    game_speed: 'Vitesse de Base',
    vibration: 'Vibres Tactiles',
    sound_vol: 'Volume des Sons',
    music_vol: 'Volume de la Musique',
    language: 'Langues de l\'Écran',
    skin_classic: 'Vert Émeraude',
    skin_neon: 'Lueur Néon Laser',
    skin_gradient: 'Dégradé Bleu Océan',
    skin_rainbow: 'Arc-en-Ciel Psy',
    skin_outline: 'Tracé Minimaliste',
    theme_default: 'Ardoise Cosmique',
    theme_grid: 'Grille Maillée',
    theme_retro: 'Écran Vert Rétro',
    theme_dark: 'Vide Total',
    theme_high_contrast: 'Contraste Noir & Blanc',
    theme_pastel: 'Douceur Glycine Pastel',
    speed_slow: 'Lent (Facile)',
    speed_normal: 'Normal (Moyen)',
    speed_fast: 'Rapide (Ardu)',
    speed_insane: 'Extrême (Fou)',
    control_swipe: 'Glisser Doigt',
    control_dpad: 'Bouton D-Pad En-bas',
    control_onetap: 'Tapotement Horloger',
    control_keyboard: 'Flèches / WASD Clavier',
    shared_text: 'J\'ai collecté {score} points et atteint {length} cases dans Serpente Ultime ! Pouvez-vous faire mieux ?',
    no_scores: 'Aucun record enregistré. À vous la couronne !',
    level_completed: 'Niveau {level} validé !',
    level_congrats: 'Préparez-vous à l\'étape suivante !',
    continue_nxt: 'Passer au Niveau {level}',
    tip_jar: 'Laisser un Pourboire',
    tip_jar_desc: 'Si vous appréciez Serpente Ultime, vous pouvez motiver son auteur !',
    replaying: 'Lecture Instant Replay...',
    stop_replay: 'Fermer Replay',
  },
  de: {
    title: 'Ultimative Schlange',
    play: 'Spiel Starten',
    classic: 'Klassik Modus',
    timed: 'Zeit-Championship',
    adventure: 'Szenario-Abenteuer',
    zen: 'Entspannendes Zen',
    endless: 'Endlos Modus',
    survival: 'Überlebensmodus',
    maze: 'Labyrinth Map',
    speedrun: 'Schnelligkeitslauf',
    boss: 'Bosskampf',
    classic_desc: 'Endloses Schlängeln, steigendes Tempo, reine Highscore-Jagd.',
    timed_desc: 'Erreiche Bestwert in 120 Sekunden. Goldene Äpfel erscheinen oft.',
    adventure_desc: 'Progressive Level (1-20). Starre Hürden und Zielvorgaben.',
    zen_desc: 'Unsterblich, Pastell-Themen, harmonische Hintergrundmusik.',
    endless_desc: 'Lockerer Modus ohne Mauern oder Eigenberührungen.',
    survival_desc: 'Schnelle unregelmäßige Block-Spawns für extreme Abenteuer.',
    maze_desc: 'Meistere vollständige Labyrinthe aus geformten Blockstrukturen.',
    speedrun_desc: 'Sammle 50 Äpfel in Bestzeit auf Ultra-Geschwindigkeit.',
    boss_desc: 'Weiche den sich bewegenden feindlichen Roboterschlangen aus.',
    settings: 'Einstellungen',
    high_scores: 'Bestenliste',
    install_app: 'PWA Web-App installieren',
    resume: 'Fortsetzen',
    restart: 'Level Neustart',
    main_menu: 'Hauptmenü',
    game_over: 'Spiel Vorbei!',
    new_high_score: 'Neuer Highscore!',
    play_again: 'Nochmal Spielen',
    share_score: 'Score Teilen',
    replay_final: 'Replay Ansehen',
    duration_active: 'Aktiv:',
    score: 'Punkte',
    high_score: 'Rekord',
    length: 'Länge',
    lives: 'Leben',
    level: 'Stufe',
    target: 'Zielpunkt',
    time: 'Zeit',
    tutorial_skip: 'Erklärung überspringen',
    tut_step_1_title: 'Wischen oder Tippen',
    tut_step_1_desc: 'Wische auf dem Bildschirm, nutze das Steuerkreuz oder die Ein-Klick-Steuerung in den Einstellungen, um die Richtung zu wechseln.',
    tut_step_2_title: 'Wachse durch Nahrung',
    tut_step_2_desc: 'Friss rote Äpfel, um zu wachsen. Erbitte Goldene Äpfel, Blitz-Geschwindigkeit, Schildkröten-Bremse oder Bonus-Sterne!',
    tut_step_3_title: 'Kraftvolle Schutzschilde',
    tut_step_3_desc: 'Finde Schilde gegen Kollisionen, x2 Multiplikatoren oder Schwanzkürzung zur Erleichterung!',
    tut_step_4_title: 'Vermeide Barrieren',
    tut_step_4_desc: 'Weiche im Abenteuer Hindernissen aus. Ohne aktiven Schutzschild bedeutet jeder Zusammenstoß das Ende.',
    wall_wrap: 'Wanddurchgang',
    wall_wrap_on: 'Durchgang Aktiv',
    wall_wrap_off: 'Feste Mauern',
    snake_skin: 'Schlangenhaut-Kosmetik',
    board_theme: 'Spielfelddesign',
    control_scheme: 'Richtungssteuerung',
    game_speed: 'Grundgeschwindigkeit',
    vibration: 'Vibration-Haptik',
    sound_vol: 'Toneffekte Lautstärke',
    music_vol: 'Musik Lautstärke',
    language: 'Bildschirmsprache',
    skin_classic: 'Smaragd-Grün',
    skin_neon: 'Neon Laserglühen',
    skin_gradient: 'Ozean Farbverlauf',
    skin_rainbow: 'Psychedelischer Regenbogen',
    skin_outline: 'Minimalistische Umrandung',
    theme_default: 'Kosmischer Schiefer',
    theme_grid: 'Klassisches Gitter',
    theme_retro: 'Retro Monochrom-Grün',
    theme_dark: 'Leere Mitternacht',
    theme_high_contrast: 'Klarer Kontrast',
    theme_pastel: 'Zen-Flieder Pastell',
    speed_slow: 'Langsam (Einfach)',
    speed_normal: 'Standard (Mittel)',
    speed_fast: 'Schnell (Schwer)',
    speed_insane: 'Wahnsinn (Hyper)',
    control_swipe: 'Gesten wischen',
    control_dpad: 'Steuerkreuz-Buttons',
    control_onetap: 'Ein-Tipp Richtungsdreh',
    control_keyboard: 'Zifferntasten / WASD',
    shared_text: 'Ich habe {score} Punkte mit Länge {length} in Ultimative Schlange erzielt! Kannst du das überbieten?',
    no_scores: 'Noch kein Highscore eingetragen. Starte die Jagd!',
    level_completed: 'Level {level} Abgeschlossen!',
    level_congrats: 'Bereite dich auf die nächste Stufe vor!',
    continue_nxt: 'Weiter zu Level {level}',
    tip_jar: 'Unterstützung für den Entwickler',
    tip_jar_desc: 'Wenn dir Ultimative Schlange gefällt, schicke ein kleines Trinkgeld!',
    replaying: 'Zeige Spiel-Wiederholung...',
    stop_replay: 'Replay Beenden',
  },
  ja: {
    title: 'アルティメット・スネーク',
    play: 'ゲーム開始',
    classic: 'クラシックモード',
    timed: 'タイムアタック',
    adventure: 'アドベンチャー',
    zen: '禅・マインドフル',
    endless: 'エンドレス（すり抜け）',
    survival: 'サバイバルモード',
    maze: '迷路パズル',
    speedrun: '極限スピードラン',
    boss: '対決AIボス',
    classic_desc: '速度上昇、壁衝突あり、エンドレスのハイスコア追及。',
    timed_desc: '120秒以内に最高得点を稼ぐ。金のリンゴが多く出現。',
    adventure_desc: '全20ステージを攻略。マップに障害物の壁や迷路が出現。',
    zen_desc: '不死身、パステル調、リラックスできるBGM。練習に最適。',
    endless_desc: '壁すり抜け可能および自己衝突による死亡が無効のリラックスモード。',
    survival_desc: '不定期なブロック生成と速度の急加速に立ち向かう。',
    maze_desc: '敷き詰められた壁迷路をぶつからずに攻略する。',
    speedrun_desc: '超ハイスピードでリンゴ50個を完食するタイムを計る。',
    boss_desc: 'プレイヤーの行動を阻止しようと追いかける敵AIヘビとの対決。',
    settings: 'ゲーム設定',
    high_scores: 'ハイスコア記録',
    install_app: 'アプリをインストール',
    resume: '再開する',
    restart: '再挑戦する',
    main_menu: 'メインメニューへ',
    game_over: 'ゲームオーバー！',
    new_high_score: '最高得点を更新！',
    play_again: 'もう一度遊ぶ',
    share_score: 'スコアをシェア',
    replay_final: '最後のリプレイ',
    duration_active: '効果継続:',
    score: 'スコア',
    high_score: 'ハイスコア',
    length: '長さ',
    lives: 'ライフ',
    level: 'レベル',
    target: '目標値',
    time: 'タイム',
    tutorial_skip: 'チュートリアルをスキップ',
    tut_step_1_title: 'スワイプ・タップで操縦',
    tut_step_1_desc: 'スワイプ操作や画面の十字キー、また設定のワンタップ方向転換モードで蛇の移動方向を切り替えます。',
    tut_step_2_title: 'リンゴを食べて成長',
    tut_step_2_desc: '赤いリンゴで成長します。希少な金のリンゴ、稲妻（高速化）、カメ（低速化）、スターなどを集めましょう！',
    tut_step_3_title: 'シールド回復・サポート効果',
    tut_step_3_desc: '壁や衝突を一度防ぐシールド、スコア２倍倍率、体を短くする「縮小」パワーアップを集めます。',
    tut_step_4_title: '障害物を回避する',
    tut_step_4_desc: 'アドベンチャーでは迷路の壁にぶつからないよう移動します。シールドがない場合、壁衝突で敗北となります。',
    wall_wrap: '壁のすり抜け',
    wall_wrap_on: 'すり抜けあり',
    wall_wrap_off: '堅い外壁あり',
    snake_skin: 'スネークデザイン',
    board_theme: 'グリッド模様デザイン',
    control_scheme: '移動コントロール',
    game_speed: '基本移動スピード',
    vibration: 'バイブレーション調整',
    sound_vol: 'ゲーム効果音',
    music_vol: 'バックグラウンド音楽',
    language: 'インターフェース言語',
    skin_classic: 'エメラルドグリーン',
    skin_neon: 'ネオン・レーザー光',
    skin_gradient: 'シー・グラデーション',
    skin_rainbow: 'レインボー・カラフル',
    skin_outline: 'ミニマル・アウトライン',
    theme_default: 'コズミック・スレート',
    theme_grid: 'クラシック方方眼デザイン',
    theme_retro: 'レトロ・モノクローム',
    theme_dark: 'ミッドナイト・ダーク',
    theme_high_contrast: 'コントラスト・ホワイト',
    theme_pastel: '禅藤パステルカラー',
    speed_slow: 'のんびり（易しい）',
    speed_normal: '通常（普通）',
    speed_fast: 'ハイスピード（難しい）',
    speed_insane: '超高速（インセイン）',
    control_swipe: 'スワイプコントロール',
    control_dpad: '画面十字キー',
    control_onetap: 'ワンタップ旋回方式',
    control_keyboard: 'キーボード WASD / 方向キー',
    shared_text: '『アルティメット・スネーク』でスコア {score} 、ヘビの長さ {length} を達成！ 私の記録を超えられますか？',
    no_scores: 'ハイスコアがまだありません。王位を狙いましょう！',
    level_completed: 'レベル {level} クリア！',
    level_congrats: '次のレベルに備えましょう！',
    continue_nxt: 'レベル {level} に進む',
    tip_jar: '開発者を支援 / チップを送る',
    tip_jar_desc: '『アルティメット・スネーク』を気に入られましたら、ご支援を検討ください。',
    replaying: '最後のリプレイを再生中...',
    stop_replay: 'リプレイを閉じる',
  },
};
